### ISSUE TITLE
Installation (Home Assistant Integration)

### ISSUE THREAD

**Issue by Naimkr27** [KaiGrassnick/py-thermotec-aeroflow-flexismart#1]
Hallo, 

danke erstmal für die Arbeit.

Ich bin neu bei Home Assistenten, weil ich auf so eine Integration gewartet habe.

Kannst du mir eine Schritt-für-Schritt-Anleitung erstellen. Habe den PIP-Befehl im Container vom Home Assistent ausgeführt und das Tool installiert, komme aber nicht weiter.

Meine Voraussetzungen:
Mini-PC mit Proxmox und einer VM mit dem Script von whiskerz007. Alternativ könnte ich eine VM mit einer QCOW2-Disk von HomeAssistent erstellen, aber weiter komme ich nicht.

Vielen Dank und viele Grüße

**Comment by KaiGrassnick** [comment]
Moin

es ist schon ein paar Tage her, dass ich angefangen habe das ding zu schreiben. Das hier ist nur die Library für die eigentliche integration. Die musst du gar nicht selbst installieren.


Hier gehts zu der Integration für Home Assistant: https://github.com/KaiGrassnick/thermotec_aeroflow


Die Integration ist auch erst in einem pre alpha stadium. Ich hab das ne zeit lang programmiert und war dann aber mit anderen Sachen / Projekten beschäftigt.

Die Integration habe ich jetzt mal mit dem aktuellen Stand hochgeladen. Es funktioniert tendenziell, aber nicht zwangsläufig perfekt. Da müsste noch etwas mehr Arbeit und Zeit rein gesteckt werden. Du kannst es aber gerne schonmal ausprobieren.

Die Anleitung findest du dort im Readme. Ist eigentlich ganz simpel.

1. Einmal das aktuelle Release runterladen.
2. Das Zip entpacken und den ganzen ordner `thermotec_aeroflow` in den ordner `<config>/custom_components` reinladen. 
 -  Da gibts verschiedene Wege... Ich hab das zip via dem Config Editor in den ordner custom_components reingeladen und bin dann via terminal / ssh in den HomeAssistant Container und hab dort mit unzip die integration entpackt.
 - Ich denke aber mal, dass bekommst du schon hin ;)
3. Wenn die Integration dann hochgeladen / entpackt im custom_components ordner liegt, einmal HomeAssistant neu starten
4. Dann via Einstellungen -> Integrationen die Integrationen Seite aufrufen. Hier einmal STRG + F5 um den Cache zu resetten bzw. eimal Browser Cache leeren.
5. Neue Integration hinzufügen -> hier dann nach Thermotec Aeroflow suchen.
6. Thermotec Aeroflow hinzufügen und warten. Das kann nen moment dauern. Anschließend sollte er nach der IP des Gateways fragen. Hier muss dann einmal die IP vom Flexismart Gateway eingetragen werden. Port kann gleich bleiben.
7. Das wars tendenziell auch schon.

**Comment by Naimkr27** [comment]
Servus,

danke für die Anleitung, hat alles funktioniert.

Gruß Naim

**Comment by KaiGrassnick** [comment]
@Naimkr27 Ich hab die Library und auch die Integration aktualisiert.
Wichtiges feature: Man kann die Temperature jetzt via einem Service setzen, damit lässt sich das ganze nun auch besser in Automatisierungen nutzen.
Außerdem sollte es jetzt auch stabiler mit mehreren Heizkörpern laufen

Leider bin ich noch nicht soweit, dass man über Updates informiert wird, also gerne hin und wieder in das Integration Projekt reinschauen ob es updates gibt.

Ich bin auch für Anregungen und Bug reports offen, gerne dort einfach ein Issue aufmachen.

**Comment by Naimkr27** [comment]
Hallo Kai,

danke für den Hinweis.
Ich fände es besser, wenn man die Temperatur scrollen kann statt jedes Mal zu tippen.

Gruß Naim

**Comment by KaiGrassnick** [comment]
Moin Naim,

ich hab das Problem nicht ganz verstanden.
Aber wenn es dir um das Design geht, da kann ich nichts ändern (zumindest nicht mit der Library oder der Integration)

Aber vielleicht ist das hier was für dich: https://github.com/nervetattoo/simple-thermostat

Grüße,
Kai

**Comment by Naimkr27** [comment]
Morgen Kai,

man muss ja z.B. für eine Temperatur für 20 Grad 40 mal tippen, ich fände es angenehmer, wenn man ein Rad hat, wo mal drehen kann ähnlich der Jahresauswahl beim Geburtstag.

Gruß

Naim

**Comment by KaiGrassnick** [comment]
Moin,

mit der Thermostat Kachel kannst du das Problemlos machen: https://www.home-assistant.io/lovelace/thermostat/
So hab ich das auch. Einfach der Anleitung in dem link folgen. Da kannst du dann einfach den Regler ziehen zum verstellen der Temperatur.

Grüße,
Kai

**Comment by mvlperera** [comment]
Hi ,

I tried to install the intergration but even after a refresh HASS is not finding it via the intergrations page. Any suggestions?

Thanks

**Comment by KaiGrassnick** [comment]
@mvlperera please make sure you use the integration. This is only the library.
Integration is here: https://github.com/KaiGrassnick/thermotec_aeroflow

**Comment by mvlperera** [comment]
Ah perfect thank you so much :)

**Comment by mvlperera** [comment]
<img width="593" alt="image" src="https://user-images.githubusercontent.com/29145084/197992712-31cd48cc-e943-423b-a6ff-33d957034941.png">
So I get this now. I can move this chat to the other repo if you perfer
